-- Hybernate doesn't seem to like multiple insert syntax so each has its own line.

INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('big','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine01','0023','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('med','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine02','0044','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine03','0003','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine04','0004','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine05','0005','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','1.29','shrt desc shrt',1,'wine06','0006','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine07','0007','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine08','0008','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine09','0009','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine10','0010','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine11','0011','http://i.imgur.com/UBLi3O3.jpg')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine12','0012','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine14','0013','')
INSERT INTO wines(bottle_size,country_of_origin,grape_type,long_description,price,short_description,vegetarian,name,product_number, picture_url) VALUES('small','uk','grape1','long description of wine is long','2.99','shrt desc shrt',1,'wine15','0014','')

